{{- define "pebble.configmap" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "pebble.fullname" . }}
  labels:
    {{- include "pebble.labels" . | nindent 4 }}
data:
  # This configmap contains Pebble's configuration file and some certificate it
  # can use for its own HTTPS traffic, as well as the root certificate that
  # signed those.
  #
  pebble-config.json: |
    {{- .Values.pebble.config | toJson | nindent 4 }}

  # A root cert and key, for use by:
  # 1. Pebble's ACME server requires TLS communication: this root cert will
  #    create a leaf cert for Pebble to use in its installed namespace.
  #
  # 2. ACME client's speaking with Pebble need to trust this root cert in order
  #    to accept Pebble's leaf cert.
  #
  # NOTE: This root cert, or its leaf certs, are unrelated to the certs Pebble
  #       will provision as an ACME server. Pebble always recreates a new root
  #       cert on each startup and use it to create certs for the ACME clients.
  #       These temporary root certs are exposed through a REST API at /roots/0
  #       on the acme-mgmt port.
  #
  # ref: https://github.com/letsencrypt/pebble/tree/master/test/certs
  {{- (.Files.Glob "files/root-cert.pem").AsConfig | nindent 2 }}
  {{- (.Files.Glob "files/root-key.pem").AsConfig | nindent 2 }}
{{- end }}

{{- include "pebble.configmap" . | fromYaml | merge .Values.pebble.merge.configmap | toYaml }}
